### ISSUE TITLE
articles 필터부분 확장하기

### ISSUE THREAD

**Issue by redgoose-dev** [redgoose-dev/goose-manager#39]
article 스킨이 `nest` 값에의해 고정되어 있는데 좀더 유연하게 사용하려면 필터 영역을 이용하는게 좋을거 같다.
많이 늘리기 부담스러운 이유가 분류와 같이 한줄을 2컬럼으로 사용하고 있기 때문에 공간이 부족하게 느껴진다.

### 개선 아이디어

- 두줄로(필터한줄, 분류한줄)로 사용
  높이가 커서 부담스럽게 느껴진다.
- 필터 부분을 드롭다운으로 나왔다 없어지게 토글링하는 방식
  이 방식은 목록에서 보이지 않는다.
- 필터 버튼을 눌러서 모달창이 나오게 하는방식
  이 방식은 목록에서 필터의 모습이 보이지 않는다.
- 사이드(왼쪽이나 오른쪽)에 필터영역을 배치하는 방식
  한눈에 필터와 같이 상태를 볼 수 있지만 목록이 좁게 느껴진다. 하지만 레이블을 붙일 수 있고, 공간을 좀더 활용할 수 있을거라는 기대감이 크다.
  가장 좋은 방법일지도..

### TODO

UI 개선하는 것이랑 article 스킨 변경하는 부분들이 주 업무

- [x] UI 개선방식 결정하기
- [x] UI 부분 코드 수정하기
- [x] 필터 부분에서 article 스킨 항목 추가하기
- [x] nest 에서 article 스킨부분 코드 삭제하기

**Comment by redgoose-dev** [comment]
사이드(왼쪽과 오른쪽) 방식으로 변경할 작업으로 예정

**Comment by redgoose-dev** [comment]
작업완료
